# Generated by Django 5.1.3 on 2024-11-23 21:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип резервной копии',
                'verbose_name_plural': 'Типы резервных копий',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Хранилище',
                'verbose_name_plural': 'Хранилища',
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип хранилища',
                'verbose_name_plural': 'Типы хранилищ',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя для подключения')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль для подключения')),
                ('ip', models.CharField(max_length=255, verbose_name='IP-адрес для подключения')),
                ('post', models.CharField(max_length=255, verbose_name='Порт для подключения')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 24, 0, 53, 14, 247313), verbose_name='Дата и время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.backuptype', verbose_name='Тип хранилища')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storage', verbose_name='Хранилище')),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
            },
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storagetype', verbose_name='Тип хранилища'),
        ),
    ]
