# Generated by Django 5.1.3 on 2024-11-23 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='storage_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='backup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 1, 30, 1, 648809), verbose_name='Дата и время создания'),
        ),
    ]
