# Generated by Django 5.1.3 on 2024-11-23 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_storage_type_storage_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='post',
            new_name='port',
        ),
        migrations.AlterField(
            model_name='backup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 1, 42, 33, 688944), verbose_name='Дата и время создания'),
        ),
    ]
