# Generated by Django 5.1.3 on 2024-11-23 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_post_backup_port_alter_backup_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='db',
            field=models.CharField(default='', max_length=255, verbose_name='База данных'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 1, 43, 17, 839518), verbose_name='Дата и время создания'),
        ),
    ]
