# Generated by Django 5.1.3 on 2024-11-24 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backup_db_alter_backup_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='location',
        ),
        migrations.AlterField(
            model_name='backup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 14, 15, 47, 669063), verbose_name='Дата и время создания'),
        ),
    ]
