# Generated by Django 5.2.15 on 2026-06-19 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_backup_location_alter_backup_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Резервная копия', 'verbose_name_plural': 'Резервные копии'},
        ),
        migrations.AlterField(
            model_name='backup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.backuptype', verbose_name='Тип резервной копии'),
        ),
    ]
