# Generated by Django 5.2.17 on 2026-09-30 15:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Хранилище по умолчанию, созданное миграцией 0007. Названия типов копий
# теперь переводятся в коде, а эти строки остаются данными, поэтому
# переименовываются в английские, только если их не меняли вручную.
DEFAULT_STORAGE = {
    "location": ("Каталог BACKUP_DIR на сервере", "BACKUP_DIR on the server"),
    "type": ("Локальный диск", "Local disk"),
}


def rename_default_storage(apps, schema_editor):
    Storage = apps.get_model("core", "Storage")
    StorageType = apps.get_model("core", "StorageType")
    old, new = DEFAULT_STORAGE["location"]
    Storage.objects.filter(location=old).update(location=new)
    old, new = DEFAULT_STORAGE["type"]
    StorageType.objects.filter(title=old).update(title=new)


def restore_default_storage(apps, schema_editor):
    Storage = apps.get_model("core", "Storage")
    StorageType = apps.get_model("core", "StorageType")
    old, new = DEFAULT_STORAGE["location"]
    Storage.objects.filter(location=new).update(location=old)
    old, new = DEFAULT_STORAGE["type"]
    StorageType.objects.filter(title=new).update(title=old)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_backup_type_code_drop_password"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(rename_default_storage, restore_default_storage),
        migrations.AlterModelOptions(
            name="backup",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "backup",
                "verbose_name_plural": "backups",
            },
        ),
        migrations.AlterModelOptions(
            name="backuptype",
            options={
                "ordering": ["id"],
                "verbose_name": "backup type",
                "verbose_name_plural": "backup types",
            },
        ),
        migrations.AlterModelOptions(
            name="storage",
            options={"verbose_name": "storage", "verbose_name_plural": "storages"},
        ),
        migrations.AlterModelOptions(
            name="storagetype",
            options={
                "verbose_name": "storage type",
                "verbose_name_plural": "storage types",
            },
        ),
        migrations.RemoveField(
            model_name="backuptype",
            name="description",
        ),
        migrations.RemoveField(
            model_name="backuptype",
            name="title",
        ),
        migrations.AlterField(
            model_name="backup",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="db",
            field=models.CharField(max_length=255, verbose_name="database"),
        ),
        migrations.AlterField(
            model_name="backup",
            name="host",
            field=models.CharField(max_length=255, verbose_name="host"),
        ),
        migrations.AlterField(
            model_name="backup",
            name="port",
            field=models.PositiveIntegerField(verbose_name="port"),
        ),
        migrations.AlterField(
            model_name="backup",
            name="size",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="file size, bytes"
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="storage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.storage",
                verbose_name="storage",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.backuptype",
                verbose_name="backup type",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="username",
            field=models.CharField(max_length=255, verbose_name="database user"),
        ),
        migrations.AlterField(
            model_name="backuptype",
            name="code",
            field=models.CharField(
                choices=[
                    ("full", "Full"),
                    ("incremental", "Incremental"),
                    ("differential", "Differential"),
                ],
                help_text="Selects the backup algorithm",
                max_length=20,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="location",
            field=models.CharField(max_length=255, verbose_name="location"),
        ),
        migrations.AlterField(
            model_name="storage",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.storagetype",
                verbose_name="storage type",
            ),
        ),
        migrations.AlterField(
            model_name="storagetype",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
    ]
