# Generated by Django 5.2.17 on 2026-09-30 20:25

import core.backends
import django.db.models.deletion
from django.db import migrations, models


def mark_existing_backups_ready(apps, schema_editor):
    """Копии, снятые до очереди, уже готовы, а их файлы лежат в BACKUP_DIR
    под прежним именем backup<id>.sql. Снимков состояния у них нет, поэтому
    базой для новых дельт они служить не будут."""
    Backup = apps.get_model("core", "Backup")
    for backup in Backup.objects.all().only("pk", "created_at"):
        Backup.objects.filter(pk=backup.pk).update(
            status="succeeded",
            file_name=f"backup{backup.pk}.sql",
            finished_at=backup.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_backup_type_translatable"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="base",
            field=models.ForeignKey(
                blank=True,
                help_text="The backup whose state this delta was compared with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependents",
                to="core.backup",
                verbose_name="base backup",
            ),
        ),
        migrations.AddField(
            model_name="backup",
            name="error_code",
            field=models.CharField(blank=True, max_length=50, verbose_name="error"),
        ),
        migrations.AddField(
            model_name="backup",
            name="error_detail",
            field=models.TextField(
                blank=True,
                help_text="Technical details for administrators; not shown to users",
                verbose_name="error details",
            ),
        ),
        migrations.AddField(
            model_name="backup",
            name="file_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="backup file"
            ),
        ),
        migrations.AddField(
            model_name="backup",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="finished at"
            ),
        ),
        migrations.AddField(
            model_name="backup",
            name="secret",
            field=models.TextField(
                blank=True, editable=False, verbose_name="encrypted password"
            ),
        ),
        migrations.AddField(
            model_name="backup",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="started at"
            ),
        ),
        migrations.AddField(
            model_name="backup",
            name="state_name",
            field=models.CharField(
                blank=True,
                help_text="Row hashes that later deltas are compared with",
                max_length=255,
                verbose_name="state file",
            ),
        ),
        migrations.AddField(
            model_name="backup",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("succeeded", "Ready"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="backend",
            field=models.CharField(
                choices=core.backends.backend_choices,
                default="local",
                help_text="Where files are written; S3 needs the BACKUP_S3_* settings",
                max_length=50,
                verbose_name="backend",
            ),
        ),
        migrations.RunPython(mark_existing_backups_ready, migrations.RunPython.noop),
    ]
