# Generated by Django 5.2.17 on 2026-09-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_backup_jobs_and_storage_backends"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="promoted_reason",
            field=models.CharField(
                blank=True,
                help_text="Set when a requested delta could not be taken and a full backup was taken instead",
                max_length=30,
                verbose_name="taken as full because",
            ),
        ),
    ]
